controller:
  state:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  trajectory:
      type: position_controllers/JointTrajectoryController
      joints:
        - J40
      constraints:
          goal_time: 0.1
      stop_trajectory_duration: 0.35

  position:
    J40:
      type: position_controllers/JointPositionController
      joint: J40
      pid: {p: 100.0, i: 0.0, d: 0.0, i_clamp: 0}

    