controller:
  state:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  trajectory:
      type: effort_controllers/JointTrajectoryController
      joints:
        - J40
      gains:
        J40: {p: 90000, i: 1000, d: 1000, i_clamp: 1.0}
      constraints:
          goal_time: 0.1
      stop_trajectory_duration: 0.35

  position:
    J40:
      type: effort_controllers/JointPositionController
      joint: J40
      pid: {p: 9000.0, i: 100.0, d: 100.0, i_clamp: 100.0}
  # effort:
  #   J40:
  #     type: effort_controllers/JointEffortController
  #     joint: J40

  effort:
      type: effort_controllers/JointGroupEffortController
      joints:
        - J40
      gains:
        J40: {p: 90000, i: 1000, d: 1000, i_clamp: 1.0}
      constraints:
          goal_time: 0.1
      stop_trajectory_duration: 0.35